version: "3"
services:
  syncthing:
    image: syncthing/syncthing:latest
    container_name: syncthing
    hostname: my-syncthing
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      # 配置文件存储位置
      - ./syncthing-config:/var/syncthing/config
      # 同步文件夹
      - ./sync-data:/var/syncthing/data
      # 你的HECO源数据文件夹
      - D:/HECO源数据:/var/syncthing/HECO源数据
    ports:
      - "8384:8384"       # Web GUI
      - "22000:22000/tcp" # 同步协议 TCP
      - "22000:22000/udp" # 同步协议 QUIC
      - "21027:21027/udp" # 本地发现
    restart: unless-stopped
    healthcheck:
      test: curl -fkLsS -m 2 127.0.0.1:8384/rest/noauth/health | grep -o --color=never OK || exit 1
      interval: 1m
      timeout: 10s
      retries: 3
